lib/explore_web/router.ex
defmodule ExploreWeb.Router do
  use ExploreWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ExploreWeb.Plugs.SetCurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExploreWeb do
    pipe_through :browser

    get "/", UserController, :index
    resources "/users", UserController

    resources "/sessions", SessionController, only: [:new, :create]
    get "/sign_out", SessionController, :delete

    resources "/registrations", RegistrationController, only: [:new, :create]

    resources "/items", ItemController

    get "/*path", ErrorController, :index

  end

  # Other scopes may use custom stacks.
  # scope "/api", ExploreWeb do
  #   pipe_through :api
  # end
end

lib/explore_web/views/layout_view.ex
defmodule ExploreWeb.LayoutView do
  use ExploreWeb, :view
end

lib/explore_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Explore · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= if @user_signed_in? do %>
      <h3>
        Signed in as: <strong><%= @current_user.username %></strong>
      </h3>
      <%= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :get, class: "btn btn-outline-primary" %>
    <% else %>
      <%= link "Sign In", to: Routes.session_path(@conn, :new), class: "btn btn-outline-primary" %>
      <%= link "Sign Up", to: Routes.registration_path(@conn, :new), class: "btn btn-outline-primary ml-md-3" %>
    <% end %>

    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>